language: crystal

addons:
  ssh_known_hosts:
    secure: "YoN4istJDMOrze7FTB/JeBIDKSMpX2J9JRuX9v8rMW+1GMygiQNry/HyYD7hDyGlvnRmWkr4MI1QipTLyiGZcD/E7FvchOZQFnyJK0s4zmWuITmWryrxF+YN3MAGojvsD2f+oyz/35O1LQn30Jbgw/t6idFOflTGUhIGGQyTZFkv5HPItOZpdpgTn0RsSy5CKdrXCuHJ55jHzGnzT4q/qhur+uMybvebvAwbolnk0e24yIWVRb+5rEMvi2Ln47GmpRVoyhWO0QesosiQabm3AcPXztsp4YrsNQs2k1asZa7UaUPRB5ErWiFK/aGjc/0S927SvMQy3Vr4w7EhnCkQgrlceCV66m+EgLzxvCU4SteDr7XVqXyQS86e+941xhAzVu7C9vbUkK1ER/xhRGd67r+b9nYB5E3qtDGnmAuj7Yt840pDLHHQjwI2/nOIq/5YCECBQN/UEf54TMGNQkPrav+/azNaaSl3diT8rE0bpGJk4DSD7Vr4uRiy8P+CfxywxTcPD2numtDBv94/hBh0AyOROP2UVc8Z5EzPKjxaZ+UpmMY4exnIDtW/gpO3KtZkWaLMvzcDu5y9edHCBrkBPV+IfC9/87RWZiFuuAUUmrg1grnSBFAHOtdJ4R8LZDEZ+C/bmdwk6dQkgf3p0kIoeli1l1MEAkyEvRyXY2SvIw0="
env:
  global:
    LOCAL_LD_PATH: ${TRAVIS_BUILD_DIR}/dynlib

before_install:
  - openssl aes-256-cbc -K $encrypted_d1bd2aab0391_key -iv $encrypted_d1bd2aab0391_iv -in .travis/id_rsa.enc -out .travis/id_rsa -d
  - shards install
  - make -C lib/sass dep
script: LIBRARY_PATH="$LOCAL_LD_PATH/lib" LD_LIBRARY_PATH="$LOCAL_LD_PATH/lib" KEMAL_ENV=test crystal spec
after_success: "[[ $TRAVIS_BRANCH == \"master\" && $TRAVIS_PULL_REQUEST == \"false\" ]] && .travis/deploy.sh"
