language: crystal
#sudo: required

before_install:
  - openssl aes-256-cbc -K $encrypted_d1bd2aab0391_key -iv $encrypted_d1bd2aab0391_iv -in .travis/id_rsa.enc -out .travis/id_rsa -d
  - crystal deps
  - make -C lib/sass dep
  #- sudo ldconfig
script: KEMAL_ENV=test crystal spec
after_success: .travis/deploy.sh
