language: ruby
rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - ruby-head
bundler_args: --with test

addons:
  ssh_known_hosts:
    - 45.56.70.141

after_success:
  - openssl aes-256-cbc -K $encrypted_1a864abad9ab_key -iv $encrypted_1a864abad9ab_iv -in deploy_key.pem.enc -out deploy_key.pem -d
  - eval "$(ssh-agent -s)" # start the ssh agent
  - chmod 600 .travis/deploy_key.pem # this key should have push access
  - ssh-add .travis/deploy_key.pem
  - git remote add deploy node@45.56.70.141:~/nickclifford.me-v2
  - git push deploy
