%YAML 1.1
---
icons:
  fa:
    github:
      link: https://github.com/nickbclifford
      title: GitHub
    envelope:
      link: mailto:nick@nickclifford.me
      title: Contact Me
    key:
      link: http://pgp.mit.edu/pks/lookup?op=get&search=0xB8D82410BCA2807D
      title: PGP Public Key
  cc:
    ETH:
      link: https://etherscan.io/address/nickclifford.eth
      title: Ethereum Address (preferred)
    LTC:
      link: https://live.blockcypher.com/ltc/address/La412SP8DBU4RJBji4hKyzWFFxCiCmMpGZ
      title: Litecoin Address
    ZEC:
      link: https://explorer.zcha.in/accounts/t1XhTL1yRrVzkt4Am1CB2FntN2yigoKD5Ty
      title: Zcash Address
    BTC:
      link: https://blockchain.info/address/19k7KRhfjfRwDnndKytBRtk5vV33zWXQrA
      title: Bitcoin Address

projects:
  -
    name: MyMICDS
    link: https://mymicds.net/
    image: /images/MyMICDS.png
    desc: A portal for organizing your student life at MICDS.
  -
    name: Pear Tutoring
    link: https://peartutoring.net/
    image: /images/PearTutoring.png
    desc: The Uber of peer tutoring. Winner of 2016 WWT STEM Hackathon!
  -
    name: Ohm
    link: https://github.com/nickbclifford/Ohm
    image: /images/Ohm.png
    desc: An extremely concise programming language designed for <a href="https://en.wikipedia.org/wiki/Code_golf">code golf</a>.

skills:
  -
    name: Ruby
    link: https://www.ruby-lang.org/en/
    devicon: ruby-plain

  # -
  #  name: Rails
  #  link: http://rubyonrails.org/
  #  devicon: rails-plain

  -
    name: Node.js
    link: https://nodejs.org/en/
    devicon: nodejs-plain

  -
    name: TypeScript
    link: https://www.typescriptlang.org/
    devicon: typescript-plain

  -
    name: PHP
    link: http://www.php.net/
    devicon: php-plain

  -
    name: Travis CI
    link: https://travis-ci.org/
    devicon: travis-plain

  -
    name: MySQL
    link: https://www.mysql.com/
    devicon: mysql-plain

  -
    name: MongoDB
    link: https://www.mongodb.com/
    devicon: mongodb-plain

  -
    name: Linux
    link: https://www.linuxfoundation.org/
    devicon: linux-plain

  -
    name: Ubuntu
    link: https://www.ubuntu.com/
    devicon: ubuntu-plain

  -
    name: Git
    link: https://git-scm.com/
    devicon: git-plain

  -
    name: Apache
    link: http://httpd.apache.org/
    devicon: apache-plain

  -
    name: Nginx
    link: http://nginx.org/
    devicon: nginx-original
