%YAML 1.1
---
icons:
  github: https://github.com/MiningPotatoes
  envelope: mailto:nick@nickclifford.me

projects:
  -
    name: MyMICDS
    link: https://mymicds.net/
    image: /images/MyMICDS.png
    desc: A portal for organizing your student life at MICDS.
  -
    name: Pear Tutoring
    link: https://peartutoring.net/
    image: /images/PearTutoring.png
    desc: The Uber of peer tutoring. Winner of 2016 WWT STEM Hackathon!
  # -
  #   name: Node-GitHub-Deployer
  #   link: https://github.com/MiningPotatoes/Node-GitHub-Deployer
  #   image: https://upload.wikimedia.org/wikipedia/commons/6/66/SMPTE_Color_Bars.svg
  #   desc: ayy lmao

skills:
  -
    name: Ruby
    link: https://www.ruby-lang.org/en/
    devicon: ruby-plain

  -
    name: Rails
    link: http://rubyonrails.org/
    devicon: rails-plain

  -
    name: Node.js
    link: https://nodejs.org/en/
    devicon: nodejs-plain

  -
    name: PHP
    link: http://www.php.net/
    devicon: php-plain

  -
    name: MySQL
    link: https://www.mysql.com/
    devicon: mysql-plain

  -
    name: Linux
    link: https://www.linuxfoundation.org/
    devicon: linux-plain

  -
    name: Ubuntu
    link: https://www.ubuntu.com/
    devicon: ubuntu-plain

  -
    name: Git
    link: https://git-scm.com/
    devicon: git-plain

  -
    name: Apache
    link: http://httpd.apache.org/
    devicon: apache-plain

  -
    name: Nginx
    link: http://nginx.org/
    devicon: nginx-original
