%YAML 1.1
---
icons:
  fa:
    github:
      link: https://github.com/nickbclifford
      title: GitHub
    envelope:
      link: mailto:nick@nickclifford.me
      title: Contact Me
    key:
      link: http://pgp.mit.edu/pks/lookup?op=get&search=0xB8D82410BCA2807D
      title: PGP Public Key
  cc:
    ETH-alt:
      link: https://etherscan.io/address/0x4530d03744D7eF769025623D31966da1e8485EEf
      title: Ethereum Address (preferred)
    XMR:
      link: monero:48EqZsAL9jS7veP3YbnTvFGZhJ8VsziRjVuedUcnZuf3PrRSwBsSZEyBeXMsSN3cmoiRSqcCDmB9bPcEQmWFa1uHAGQPkDf
      title: Monero Address
    LTC-alt:
      link: https://live.blockcypher.com/ltc/address/La412SP8DBU4RJBji4hKyzWFFxCiCmMpGZ
      title: Litecoin Address
    BTC-alt:
      link: https://blockchain.info/address/19k7KRhfjfRwDnndKytBRtk5vV33zWXQrA
      title: Bitcoin Address

projects:
  -
    name: MyMICDS
    link: https://mymicds.net/
    image: /images/MyMICDS.png
    desc: A portal for organizing your student life at MICDS.
  -
    name: Pear Tutoring
    link: https://peartutoring.net/
    image: /images/PearTutoring.png
    desc: The Uber of peer tutoring. Winner of 2017 WWT STEM Hackathon!
  -
    name: navigatAR
    link: https://github.com/michaelgira23/navigatAR
    image: /images/navigatAR.png
    desc:  Finding your way through buildings and campuses through the power of augmented reality. Awarded third place at 2018 WWT STEM Hackathon!
  -
    name: Ohm
    link: https://github.com/nickbclifford/Ohm
    image: /images/Ohm.png
    desc: An extremely concise programming language designed for code golf.
  -
    name: Broccoli/Cauliflower
    link: https://github.com/broccoli-lang/Broccoli
    image: /images/broccoli.png
    desc: An open-source reimplementation of the Broccoli language.

skills:
  -
    name: Ruby
    link: https://www.ruby-lang.org/en/
    devicon: ruby-plain

  # -
  #  name: Rails
  #  link: http://rubyonrails.org/
  #  devicon: rails-plain

  -
    name: Node.js
    link: https://nodejs.org/en/
    devicon: nodejs-plain

  -
    name: TypeScript
    link: https://www.typescriptlang.org/
    devicon: typescript-plain

  -
    name: PHP
    link: http://www.php.net/
    devicon: php-plain

  -
    name: C#
    link: https://docs.microsoft.com/en-us/dotnet/csharp/
    devicon: csharp-plain

  -
    name: Travis CI
    link: https://travis-ci.org/
    devicon: travis-plain

  -
    name: MySQL
    link: https://www.mysql.com/
    devicon: mysql-plain

  -
    name: MongoDB
    link: https://www.mongodb.com/
    devicon: mongodb-plain

  -
    name: Linux
    link: https://www.linuxfoundation.org/
    devicon: linux-plain

  -
    name: Ubuntu
    link: https://www.ubuntu.com/
    devicon: ubuntu-plain

  -
    name: Git
    link: https://git-scm.com/
    devicon: git-plain

  -
    name: Apache
    link: http://httpd.apache.org/
    devicon: apache-plain

  -
    name: Nginx
    link: http://nginx.org/
    devicon: nginx-original
